<?php
//VARS
$title 				= 'Powerplay People | Inschrijven';
$body_title 		= 'Inschrijven';
$body_text			= 'Schrijf je snel in voor Powerplay People!<br /><br />';
$form				= '<form method="post" action="inschrijven">
						<input type="hidden" name="to" value="oof2000@hotmail.com" />
						<label for="Naam">Naam</label><br />
							<input type="text" name="naam" placeholder="Naam" /><br />				
						<label for="Email">Email</label><br />
							<input type="text" name="email" placeholder="Email" /><br />
						<label for="Onderwerp">Onderwerp</label><br />
							<input type="text" name="onderwerp" placeholder="Onderwerp" /><br />
						<label for="Text">Text</label><br />
							<textarea name="text" placeholder="Geef hier een korte motivatie.."></textarea>
						<input class="button" type="submit" name="submit" value="Verzend" /><br />
						
						<?php echo $outcome; ?>
						</form>';

//EMAILSCRIPT
	$naam =  $_POST['naam'];
	$email = $_POST['email'];	
	$onderwerp = $_POST['onderwerp'];	
	$text = $_POST['text'];	

	$message = "Powerplay inschrijving via de website:" . 
				"\n\n" . 
				"Email:\n " . $email . "\n\n" . 
				"Naam: \n" . $naam . "\n\n" . 
				"Onderwerp: \n" . $onderwerp . "\n\n\n" . 
				"Text: \n" . $text . "\n\n" . 
				"This mail is automatically generated by POWERPLAYPEOPLE WEBSITE";

	$to = $_REQUEST['to'];
	$subject = "PP INSCHRIJVING";
	$headers = 'From: yourwebsite@powerplaypeople.com' . "\r\n" .
				'X-Mailer: PHP/' . phpversion();;
	$send = $_REQUEST['submit'];		

	if(isset($send)) 
	{
		if(filter_var($email, FILTER_VALIDATE_EMAIL))
		{
			$result = mail($to, $subject, $message, $headers);		
			$outcome = "It worked!";	
		}
		else
		{	
			$outcome = "It worked! but not a valid email.";
		}
	} 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
	<!-- Meta -->
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	
	<!-- Title -->
	<title><?php echo $title; ?></title>
	
	<!-- CSS -->
	<link rel="stylesheet" href="css/main.css" type="text/css" media="screen" charset="utf-8" />
	<link rel="stylesheet" type="text/css" href="./fancybox/jquery.fancybox-1.3.4.css" media="screen" />	
	
	<!-- JS -->
	<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
	<script type="text/javascript" src="fancybox/jquery.fancybox-1.3.4.pack.js"></script>
	<script type="text/javascript" src="js/jquery.tinyscrollbar.min.js"></script>
	<script type="text/javascript" src="js/scrollbar.js"></script>	
	<script type="text/javascript" src="js/lightbox.js"></script>
</head>

<body>
	<!-- BG IMAGE -->
	<div id="bg_image">
		<img id="background" src="images/adam.jpg" alt="" title="" />		
	</div>

	<!-- CONTAINER -->
	<div id="IE_body">
		<div id="container">
		
			<!-- Logo -->
			<div id="logo">
				<?php require('required/logo.html') ;?>
			</div>
			
			<!-- Social Media -->
			<div id="social">
				<ul>
					<li id="fb"><a href="http://www.facebook.com/pages/Powerplay-People/222677637755563" target="_blank"></a></li>
					<li id="tw"><a href="http://twitter.com/#!/powerplaypeople" target="_blank"></a></li>
					<li id="li"><a href="http://www.linkedin.com/company/powerplay-people" target="_blank"></a></li>
				</ul>	
			</div>
			
			<!-- Menu -->
			<div id="menu_left">
				<?php require('required/menu_left.html') ;?>
			</div>
				
			<!-- Body Content -->	
			<div id="body_content">
				<h1><?php echo $body_title; ?></h1>
				<div id="body_content_input">
					<div id="scrollbar1">
						<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
						<div class="viewport">
							 <div class="overview">
								<?php echo $body_text; ?>   
								<?php echo $form; ?>   
								
							</div>
						</div>
					</div>	
				</div>	
			</div>

			
			<div id="menu_bottom">
				<?php require('required/menu_bottom.html') ;?>
			</div>		
			
			
			<!-- Wieber Cut -->
			<div class="wieber_cut">
				&nbsp;
			</div>		
			
			<!-- Wieber -->
			<div class="wieber">
				&nbsp;
			</div>
		</div>	
	</div>

	
</body>	
</html>